Print out start up exception with greater detail to help debugging
During the setup of weather-staiton directly from git repository, I did not follow all the 
instructions since I only wanted at temp sensor. A result of that was incorrect config 
for the Python scripts and exceptions during startup. To figure out what was happening
I increased the debuggability of the interrupt_daemon.py so that the actual exception
was printed (and not just the exception during shutdown).

Output before this change:
	$ sudo ~/weather-station/interrupt_daemon.py start
	PID: 4911
	Traceback (most recent call last):
	  File "/home/pi/weather-station/interrupt_daemon.py", line 207, in <module>
	    interrupt_daemon(server_port).start()
	  File "/home/pi/weather-station/interrupt_daemon.py", line 187, in start
	    self.skt.shutdown(socket.SHUT_RDWR)
	AttributeError: 'interrupt_daemon' object has no attribute 'skt'

Output after this change:

	$ sudo ~/weather-station/interrupt_daemon.py start
	PID: 5220
	Exection.
	Failed to add edge detection
	Traceback (most recent call last):
	  File "/home/pi/weather-station/interrupt_daemon.py", line 173, in start
	    self.setup()
	  File "/home/pi/weather-station/interrupt_daemon.py", line 88, in setup
	    self.wind = wind_speed_interrupt_watcher(9.0, 5, 1) #Maplin anemometer = radius of 9 cm, was 17 on prototype
	  File "/home/pi/weather-station/interrupt_daemon.py", line 50, in __init__
	    super(wind_speed_interrupt_watcher, self).__init__(sensorPin, bounceTime, peak_sample = 5, peak_monitor = True)
	  File "/home/pi/weather-station/interrupt_daemon.py", line 18, in __init__
	    GPIO.add_event_detect(sensorPin, GPIO.FALLING, callback=self.interrupt_call_back, bouncetime=bounceTime)
	RuntimeError: Failed to add edge detection
	----------------
	Traceback (most recent call last):
	  File "/home/pi/weather-station/interrupt_daemon.py", line 207, in <module>
	    interrupt_daemon(server_port).start()
	  File "/home/pi/weather-station/interrupt_daemon.py", line 187, in start
	    self.skt.shutdown(socket.SHUT_RDWR)
	AttributeError: 'interrupt_daemon' object has no attribute 'skt'